version: '3'

services:
  api-internal:
    build: ./api-internal
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=your_jwt_secret
    networks:
      - app-network

  api-external:
    build: ./api-external
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=your_jwt_secret
    networks:
      - app-network

  admin-dashboard:
    build: ./admin-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api-internal
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-internal
      - api-external
      - admin-dashboard
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
